spring:
  application:
    name: bank-simulation-service
  datasource:
    url:  jdbc:mysql://localhost:3306/bank-simulation-service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER:root}
    password: ${ENV_ROOT_PASSWORD:bank}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true

logging:
  level:
    banking.api: debug


server:
  error:
    include-stacktrace: on_param
    include-binding-errors: always
    include-message: always
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 20